# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

setopt append_history
setopt no_sharehistory
setopt no_incappendhistory

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# My Aliases
if [[ -s "$HOME/.myaliases.zsh" ]]; then
    source $HOME/.myaliases.zsh
fi

# MANPATH
export MANPATH="$JAVA_HOME/man:`manpath`"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ -s ~/.p10k.zsh ]] && source ~/.p10k.zsh

[[ -s ~/.sudo.zsh ]] && source ~/.sudo.zsh

# Secretive app
#export SSH_AUTH_SOCK=/Users/r3/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/socket.ssh

compdef _kubectl k
